### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adrianeboyd** [Christof93/SentStructure#1]
I'd like to be able to include SentStructure.js as part of an ANNIS visualizer (see https://github.com/korpling/ANNIS/pull/593) Would it be possible for you to release it under a license that allows it to be included/modified in other projects? One suggestion is the Apache License (https://apache.org/licenses/LICENSE-2.0) but obviously it would be up to you. Thanks!

**Comment by Christof93** [comment]
Hello,

I added the license :)

Glad you are considering to use the code. Its been a while since I worked on this, hope it works well.

**Comment by adrianeboyd** [comment]
Thanks so much for your quick reply!
